version: "3"
services:
  postgres:
    image: postgres:13.1
    container_name: postgres
    env_file:
      - ./config/airflow/airflow.env
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"

  airflow:
    image: airflow:2.6.1-python-3.10
    container_name: airflow
    env_file:
      - ./config/airflow/airflow.env
    restart: unless-stopped
    ports:
    - "9099:8080"
    depends_on:
    - postgres
    volumes:
      - ./workspace/airflow/dags:/opt/airflow/dags    

volumes:
  postgres: