version: '3'
services:
  jupyterlab:
    image: jupyterlab:python-3.10.11-spark-3.3.2
    container_name: jupyterlab
    ports:
      - 8888:8888
      - 4040-4045:4040-4045
    volumes:
      - ./workspace/jupyterlab:/opt/jupyterlab
      - ./config/jupyterlab:/root/.jupyter
    networks:
      - big-data
    
networks:
  big-data:
    external: true