apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-worker
spec:
  selector:
    matchLabels:
      app: airflow-worker
  template:
    metadata:
      labels:
        app: airflow-worker
    spec:
      containers:
      - name: airflow-worker
        image: airflow:2.7.1-python-3.10.11
        imagePullPolicy: "IfNotPresent"
        envFrom:
          - configMapRef:
              name: airflow-env
        args: [worker]
      volumes:
        - name: airflow-dags
          persistentVolumeClaim: 
            claimName: airflow-dags-pvc
        - name: airflow-logs
          persistentVolumeClaim:
            claimName: airflow-logs-pvc
        - name: airflow-plugins
          persistentVolumeClaim:
            claimName: airflow-plugins-pvc
