apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-flower
spec:
  selector:
    matchLabels:
      app: airflow-flower
  template:
    metadata:
      labels:
        app: airflow-flower
    spec:
      containers:
      - name: airflow-flower
        image:  airflow:2.7.1-python-3.10.11
        imagePullPolicy: "IfNotPresent"
        ports:
        - containerPort: 5555
        envFrom:
          - configMapRef:
              name: airflow-env
        command: [flower]