apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-webserver
spec:
  selector:
    matchLabels:
      app: airflow-webserver
  template:
    metadata:
      labels:
        app: airflow-webserver
    spec:
      SecurityContext:
        runAsUser: 1001  
        fsGroup: 2000
      containers:
      - name: airflow-webserver
        image: airflow:2.7.1-python-3.10.11
        imagePullPolicy: "IfNotPresent"
        ports:
        - containerPort: 8080
        envFrom:
          - configMapRef:
              name: airflow-env
        volumeMounts: 
          - mountPath: /opt/airflow/dags
            name: airflow-dags
          - mountPath: /opt/airflow/logs
            name: airflow-logs
          - mountPath: /opt/airflow/plugins
            name: airflow-plugins
        args: [webserver]
      volumes:
        - name: airflow-dags
          persistentVolumeClaim: 
            claimName: airflow-dags-pvc
        - name: airflow-logs
          persistentVolumeClaim:
            claimName: airflow-logs-pvc
        - name: airflow-plugins
          persistentVolumeClaim:
            claimName: airflow-plugins-pvc
