apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-scheduler
spec:
  selector:
    matchLabels:
      app: airflow-scheduler
  template:
    metadata:
      labels:
        app: airflow-scheduler
    spec:
      containers:
      - name: airflow-scheduler
        image: airflow:2.7.1-python-3.10.11
        imagePullPolicy: "IfNotPresent"
        envFrom:
          - configMapRef:
              name: airflow-env
        command: [scheduler]