apiVersion: v1
kind: Service
metadata:
  name: airflow-webserver
  labels:
    app: airflow-webserver
spec:
  selector:
    app: airflow-webserver
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30001
